# Generated by Django 5.0 on 2023-12-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_voter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='grader',
            new_name='gender',
        ),
    ]
