# Generated by Django 5.0.1 on 2024-01-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_grader_voter_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='voter',
            name='region',
            field=models.CharField(max_length=200),
        ),
    ]
